#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Lint&Prettier
npx lint-staged

# Обновление руководства из readme в документацию
  # Удаление файла
rm -f ./docs/src/content/docs/guides/readme.md
  # Копирование файла
cp ./README.md ./docs/src/content/docs/guides/readme.md

# Билд документации
cd ./docs && npm run build