#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm install

# Lint&Prettier
npx lint-staged

# Обновление руководства из readme в документацию
    # Добавление заголовка в README перед копированием
echo "---\ntitle: GigaChatJS\ndescription: Начните работу c GigaChatAPI.\n---\n\n$(cat ./readme.md)" > ./docs/src/content/docs/guides/readme.md

# Билд документации
cd ./docs && npm install &&  npm run build

git add .